name: Yarn Publish
on:
  release:
    types:
      - published
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
          scope: '@marcol'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: yarn publish
