name: Yarn Publish
on:
  release:
    types:
      - created
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '10'
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '10'
          cmd: lint # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '10'
          cmd: test # will run `yarn test` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '10'
          auth-token: ${{ secrets.NPM_TOKEN }}
          cmd: publish # will run `yarn test` command
